suggested_queries = [
	"What review level breaches have happened over the past week?",
	"Which instruments have incurred new review level breaches over the past week?",
	"Where has the review status changed over the past week?",
	"Give me recent changes in review status",
	"How many instruments have exceeded a review level?",
	"Summarise current review level exceedances",
	"What is the greatest settlement on site at the moment?",
	"Where is the maximum settlement on site?",
	"What was the maximum vibration read over the past week?",
	"What is the lowest groundwater level now?",
	"What is the greatest settlement that has happened on site?",
	"Where has settlement been greatest on site?",
	"What has been the highest vibration reading since the start of the project?",
	"What was the lowest recorded groundwater level ever?",
	"What is the greatest settlement rate over the past week?",
	"Where has settlement changed by more than 5mm over the past week?",
	"How quickly are inclinometers moving?",
	"How are markers with settlement changes greater than 5mm over the past week grouped on site?",
	"Have there been any unusual changes over the last week?",
	"Any sudden settlements over the past week?",
	"Any movements out of the ordinary since last Friday?",
	"Give me the top three abnormal events that have happened this week",
	"Are inclinometer movements accelerating?",
	"What is the maximum change in deflection at inclinometers over the past week?",
	"What is the depth of maximum deflection at each inclinometer on site?",
	"Summarise maximum deflections at all inclinometers",
	"Is there any correlation between settlements and groundwater levels over the past week?",
	"How are settlements that occurred between last Friday and the Friday before clustered?",
	"In which areas on site are settlements increasing most rapidly?",
	"Is there anywhere on site where groundwater levels are persistently dropping?",
	"How many new instruments were installed since last Monday?",
	"How many building settlement markers are there in each contract?",
	"List the instruments installed over the past month and group by contract",
	"Which instruments have been missing readings for longer than the elapsed time review set for them?",
	"Which instruments have not been read since last Tuesday?",
	"Summarise when the last reading was taken at each settlement marker on site",
	"What is the typical monitoring frequency at piezometers?",
	"Summarise the days with missing vibration readings over the past month",
	"Give me a list of instruments which have missed readings for more than a week at a time since project start",
	"Plot a map of review level breaches over the past week",
	"Plot a map showing instruments incurring new review level breaches over the past week",
	"Plot a map showing where review status has changed over the past week",
	"Plot a map showing recent changes in review status",
	"Plot a map showing instruments which have exceeded a review level",
	"Plot a map showing current review level exceedances",
	"Plot the change in settlement with time at the marker with the greatest settlement on site at the moment",
	"Plot a map showing where the settlement is maximum on site",
	"Plot time series vibration readings at the instrument reading the highest vibrations over the past week",
	"Plot the change in groundwater level with time at the instrument with the lowest groundwater level now",
	"Plot a map showing where the settlement is greatest on site",
	"Plot time series vibration readings at the instrument with the highest vibration reading since project start",
	"Plot the change in groundwater level with time at the instrument recording the lowest ever groundwater level",
	"Plot the change in settlement with time at the marker with the greatest settlement rate over the past week",
	"Plot a map showing the change in settlement over the past week",
	"Plot a map showing the change in settlement since last Friday",
	"Plot time series deflection at the inclinometer with the greatest rate of movement at the moment",
	"Plot a map showing the change in inclinometer deflection over the past week",
	"Plot a map showing current inclinometer deflections",
	"Plot a map showing the change in settlement between last Friday and this Friday",
	"Plot a map showing changes in groundwater level from last Friday to the Monday after",
	"Plot the change in settlement with time at the marker settling most rapidly",
	"Plot a map showing changes in groundwater level over the past three months",
]